import type { DataQualityArtifact } from "@/lib/types";
import { ChartCard } from "@/components/ChartCard";
import { OutlierChart } from "@/components/OutlierChart";

const label = (value: string) => value.replaceAll("_", " ");
const number = (value: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(value);

export function DataQualityPanel({ data }: { data: DataQualityArtifact }) {
  return <div className="space-y-4"><div className="grid gap-4 md:grid-cols-3"><ChartCard eyebrow="Completeness" title="Fields are accounted for"><p className="font-display text-4xl">{data.completeness.every((item) => item.missing === 0) ? "100%" : `${Math.min(...data.completeness.map((item) => item.completeness)).toFixed(1)}%`}</p><p className="mt-2 text-sm text-muted">Across {data.completeness.length} exported columns</p></ChartCard><ChartCard eyebrow="Duplicates" title="Unique records"><p className="font-display text-4xl">{number(data.duplicates.uniqueRecords)}</p><p className="mt-2 text-sm text-muted">{number(data.duplicates.count)} duplicate rows found</p></ChartCard><ChartCard eyebrow="Validity" title="Range checks"><p className="font-display text-4xl">{data.validity.every((item) => item.outOfRange === 0) ? "Pass" : "Review"}</p><p className="mt-2 text-sm text-muted">Four analytical measures checked</p></ChartCard></div><div className="grid gap-4 lg:grid-cols-[1.05fr_0.95fr]"><ChartCard eyebrow="IQR method" title="Outlier counts"><OutlierChart data={data.outliers.map((item) => ({ metric: label(item.metric), count: item.count }))} /></ChartCard><ChartCard eyebrow="Field register" title="Completeness by column"><div className="overflow-x-auto"><table className="w-full min-w-[420px] text-left text-sm"><thead className="border-b border-line text-xs uppercase tracking-[0.1em] text-muted"><tr><th className="pb-3 font-normal">Column</th><th className="pb-3 font-normal">Type</th><th className="pb-3 text-right font-normal">Missing</th><th className="pb-3 text-right font-normal">Unique</th></tr></thead><tbody>{data.completeness.map((item) => <tr key={item.column} className="border-b border-line last:border-0"><td className="py-3 capitalize">{label(item.column)}</td><td className="py-3 font-mono text-xs text-muted">{item.dtype}</td><td className="py-3 text-right font-mono">{number(item.missing)}</td><td className="py-3 text-right font-mono">{number(item.uniqueValues)}</td></tr>)}</tbody></table></div></ChartCard></div></div>;
}