"use client";

import { useState } from "react";
import { predictActivityBaseline, predictCaloriesBaseline } from "@/lib/predict";

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-xs uppercase tracking-[0.1em] text-muted">{label}</span>{children}</label>; }
const inputClass = "w-full border border-line bg-paper px-3 py-3 font-mono text-sm outline-none focus:border-cobalt";

export function PredictionForm({ categories }: { categories: string[] }) {
  const [activity, setActivity] = useState<string>();
  const [calories, setCalories] = useState<number>();
  return <div className="grid gap-4 lg:grid-cols-2"><form className="border border-line p-6" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setActivity(predictActivityBaseline(Number(form.get("steps")), Number(form.get("heartRate")))); }}><p className="font-mono text-xs uppercase tracking-[0.14em] text-cobalt">Classifier</p><h2 className="mt-2 font-display text-2xl">What was the activity?</h2><div className="mt-8 grid gap-4 sm:grid-cols-2"><Field label="Steps"><input className={inputClass} type="number" name="steps" defaultValue="5000" min="0" max="25000" /></Field><Field label="Average heart rate"><input className={inputClass} type="number" name="heartRate" defaultValue="120" min="40" max="220" /></Field></div><button className="mt-6 bg-ink px-5 py-3 text-sm text-paper hover:bg-cobalt" type="submit">Estimate activity</button>{activity && <p className="mt-8 border-t border-line pt-5 text-sm">Estimated activity <strong className="ml-2 font-display text-2xl capitalize text-cobalt">{activity.replaceAll("_", " ")}</strong></p>}</form><form className="border border-line p-6" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setCalories(predictCaloriesBaseline(Number(form.get("steps")), Number(form.get("heartRate")), Number(form.get("sleepHours")), String(form.get("activity")))); }}><p className="font-mono text-xs uppercase tracking-[0.14em] text-signal">Regressor</p><h2 className="mt-2 font-display text-2xl">How many calories?</h2><div className="mt-8 grid gap-4 sm:grid-cols-2"><Field label="Activity"><select className={inputClass} name="activity" defaultValue={categories[0]}>{categories.map((category) => <option key={category}>{category}</option>)}</select></Field><Field label="Steps"><input className={inputClass} type="number" name="steps" defaultValue="8000" min="0" max="25000" /></Field><Field label="Average heart rate"><input className={inputClass} type="number" name="heartRate" defaultValue="130" min="40" max="220" /></Field><Field label="Sleep hours"><input className={inputClass} type="number" name="sleepHours" defaultValue="7.5" min="0" max="24" step="0.1" /></Field></div><button className="mt-6 bg-ink px-5 py-3 text-sm text-paper hover:bg-cobalt" type="submit">Estimate calories</button>{calories !== undefined && <p className="mt-8 border-t border-line pt-5 text-sm">Estimated calories <strong className="ml-2 font-display text-2xl text-signal">{Math.round(calories).toLocaleString()} kcal</strong></p>}</form></div>;
}