import Link from "next/link";
import { ArrowRight, Database, ScanSearch } from "lucide-react";
import { StatCard } from "@/components/StatCard";
import { modelMetricsData, overviewData } from "@/lib/data";

export default function OverviewPage() {
  return <div className="mx-auto max-w-[1440px] px-5 py-14 md:px-10 md:py-24">
    <section className="grid gap-12 border-b border-ink pb-16 lg:grid-cols-[1.35fr_0.65fr] lg:gap-24">
      <div><p className="mb-8 font-mono text-xs uppercase tracking-[0.18em] text-cobalt">01 / Analytical platform</p><h1 className="max-w-4xl font-display text-5xl leading-[0.98] tracking-[-0.04em] md:text-8xl">Movement,<br />made legible.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-muted">A measured view of 358,497 fitness records across six months, turning daily signals into patterns you can inspect.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/exploratory" className="inline-flex items-center gap-3 bg-ink px-5 py-3 text-sm text-paper transition-colors hover:bg-cobalt">Explore the data <ArrowRight size={16} /></Link><Link href="/insights" className="inline-flex items-center gap-3 border border-line px-5 py-3 text-sm transition-colors hover:border-ink">Read the findings</Link></div></div>
      <div className="flex flex-col justify-end border-l border-line pl-6 lg:pl-10"><p className="font-mono text-xs uppercase tracking-[0.18em] text-muted">The collection</p><p className="mt-5 font-display text-4xl tracking-[-0.03em]">Apr-Sep<br />2023</p><div className="mt-8 grid grid-cols-2 gap-x-6 gap-y-5 border-t border-line pt-5 text-sm"><span className="text-muted">Users</span><span className="font-mono text-right">1,959</span><span className="text-muted">Activities</span><span className="font-mono text-right">07</span><span className="text-muted">Storage</span><span className="font-mono text-right">Parquet</span></div></div>
    </section>
    <section className="py-16"><div className="mb-8 flex items-end justify-between"><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-cobalt">At a glance</p><h2 className="mt-3 font-display text-3xl tracking-[-0.03em]">The first read</h2></div><span className="hidden font-mono text-xs text-muted md:block">EXPORT / {overviewData.dateRange.start} - {overviewData.dateRange.end}</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Records" value={overviewData.rowCount.toLocaleString()} detail="daily observations" /><StatCard label="Users" value={overviewData.userCount.toLocaleString()} detail="distinct profiles" /><StatCard label="Average steps" value={Math.round(overviewData.averageSteps).toLocaleString()} detail="per record" /><StatCard label="Average calories" value={Math.round(overviewData.averageCalories).toLocaleString()} detail="burned per record" /></div></section>
    <section className="grid gap-12 border-t border-line py-16 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-cobalt">What is inside</p><h2 className="mt-3 max-w-md font-display text-3xl tracking-[-0.03em]">A fixed cohort, made inspectable.</h2><p className="mt-5 max-w-md leading-7 text-muted">The dataset covers {overviewData.dateRange.days} days, {overviewData.activityCount} activity types, and a consistent set of movement and recovery signals. Every view is derived from the same exported source.</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="border-l-2 border-cobalt pl-5"><p className="font-mono text-xs text-muted">01</p><p className="mt-6 font-display text-xl">Movement</p><p className="mt-2 text-sm text-muted">Steps, calories, and activity mix over time.</p></div><div className="border-l-2 border-signal pl-5"><p className="font-mono text-xs text-muted">02</p><p className="mt-6 font-display text-xl">Recovery</p><p className="mt-2 text-sm text-muted">Sleep and heart-rate signals placed beside activity.</p></div><div className="border-l-2 border-ink pl-5"><p className="font-mono text-xs text-muted">03</p><p className="mt-6 font-display text-xl">Models</p><p className="mt-2 text-sm text-muted">Classifier accuracy: {modelMetricsData.activityClassifier.heldOutAccuracy === null ? "not available" : `${(modelMetricsData.activityClassifier.heldOutAccuracy * 100).toFixed(1)}%`}.</p></div><div className="border-l-2 border-line pl-5"><p className="font-mono text-xs text-muted">04</p><p className="mt-6 font-display text-xl">Quality</p><p className="mt-2 text-sm text-muted">Exported checks keep the analytical surface honest.</p></div></div></section>
    <section className="grid gap-4 border-t border-line pt-8 md:grid-cols-3"><Link href="/exploratory" className="group border border-line p-6 transition-colors hover:border-cobalt"><Database size={20} strokeWidth={1.5} className="text-cobalt" /><h3 className="mt-12 font-display text-xl">Explore patterns</h3><p className="mt-2 text-sm text-muted">Compare activity, health, time, and user behavior.</p><ArrowRight size={16} className="mt-8 transition-transform group-hover:translate-x-1" /></Link><Link href="/insights" className="group border border-line p-6 transition-colors hover:border-cobalt"><ScanSearch size={20} strokeWidth={1.5} className="text-cobalt" /><h3 className="mt-12 font-display text-xl">Inspect quality</h3><p className="mt-2 text-sm text-muted">See completeness, ranges, outliers, and findings.</p><ArrowRight size={16} className="mt-8 transition-transform group-hover:translate-x-1" /></Link><Link href="/predict" className="group border border-line p-6 transition-colors hover:border-cobalt"><span className="font-mono text-xl text-cobalt">ƒ(x)</span><h3 className="mt-12 font-display text-xl">Test a profile</h3><p className="mt-2 text-sm text-muted">Run an instant client-side baseline prediction.</p><ArrowRight size={16} className="mt-8 transition-transform group-hover:translate-x-1" /></Link></section>
  </div>;
}