export type ActivityType = string;
export type DateString = string;

export interface OverviewArtifact { generatedAt: string; rowCount: number; userCount: number; activityCount: number; averageSteps: number; averageCalories: number; averageHeartRate: number; averageSleepHours: number; dateRange: { start: DateString; end: DateString; days: number }; activities: Array<{ activityType: ActivityType; count: number; share: number }>; }
export interface ActivityAnalysisArtifact { categories: ActivityType[]; summary: Array<{ activityType: ActivityType; count: number; steps: MetricSummary; calories: MetricSummary; heartRate: MetricSummary; sleepHours: MetricSummary }>; stepsCaloriesSample: Array<{ steps: number; calories: number; activityType: ActivityType }>; heartRateCaloriesSample: Array<{ heartRate: number; calories: number; activityType: ActivityType }>; histograms: Record<string, HistogramBin[]>; }
export interface MetricSummary { mean: number; median: number; std: number; }
export interface HistogramBin { start: number; end: number; count: number; }
export interface HealthMetricsArtifact { numericColumns: string[]; correlation: number[][]; heartRateByActivity: Array<{ activityType: ActivityType; average: number }>; sleepByActivity: Array<{ activityType: ActivityType; average: number }>; heartRateHistogram: HistogramBin[]; sleepHistogram: HistogramBin[]; }
export interface TemporalArtifact { daily: Array<{ date: DateString; steps: number; calories: number; heartRate: number }>; weekdays: Array<{ day: string; steps: number; calories: number; count: number }>; }
export interface SegmentationArtifact { method: "kmeans" | "activity-band-fallback"; features: ["avgSteps", "avgCalories", "avgHeartRate"]; users: Array<{ userId: string | number; avgSteps: number; avgCalories: number; avgHeartRate: number; cluster: number }>; clusters: Array<{ cluster: number; users: number; avgSteps: number; avgCalories: number; avgHeartRate: number; label: string; message: string }>; }
export interface DataQualityArtifact { statistics: Array<{ metric: string; mean: number; median: number; std: number; min: number; max: number; q1: number; q3: number; iqr: number; skewness: number; kurtosis: number }>; completeness: Array<{ column: string; missing: number; completeness: number; dtype: string; uniqueValues: number; sampleValue: string }>; duplicates: { count: number; percentage: number; uniqueRecords: number }; validity: Array<{ metric: string; expectedMin: number; expectedMax: number; outOfRange: number; validPercentage: number }>; outliers: Array<{ metric: string; count: number; percentage: number; lowerBound: number; upperBound: number }>; findings: { mostPopularActivity: ActivityType; averageSteps: number; highPerformerPercentage: number; averageHeartRate: number; averageSleepHours: number; heartRateMin: number; heartRateMax: number; stepsCaloriesCorrelation: number; heartRateCaloriesCorrelation: number; mostEfficientActivity: ActivityType }; }
export interface ModelMetricsArtifact { activityClassifier: { heldOutAccuracy: number | null }; caloriesRegressor: { heldOutR2: number | null; heldOutRmse: number | null }; methodology?: string; }
export interface ModelEvalSampleArtifact { sampleSize: number; classification: { accuracy: number; labels: string[]; confusionMatrix: number[][]; report: Record<string, Record<string, number> | number>; source: "baseline" | "trained-model" }; regression: { rmse: number; r2: number; pairs: Array<{ actual: number; predicted: number }>; source: "baseline" | "trained-model" }; }